#!/bin/sh

set -eu

[ 1 = "$$" ]
[ ! -f /proc/version ]

trap 'exec /bin/sh' EXIT

mount -t proc -o nosuid,nodev,noexec none /proc
mount -t sysfs -o nosuid,nodev,noexec none /sys
mount -t devtmpfs -o nosuid,noexec none /dev

[ -r /scripts/premount-script ] && . /scripts/premount-script

SEQ=0
while [ ! -e "$autoserver_boot_dev" ]; do
	sleep 2
	SEQ="$((SEQ+1))"
	if [ "$SEQ" -gt 10 ]; then
		break
	fi
	printf 'Waiting for %s... (attempt %d)\n' "$autoserver_boot_dev" "$SEQ"
done

mount -t "${autoserver_boot_fstype:-vfat}" -o "${autoserver_boot_opts:-ro}" "$autoserver_boot_dev" "/boot_disk"
[ -e /etc/alternatives ] || ln -s /rofs_root/etc/alternatives /etc/alternatives
mount -t squashfs -o ro,nosuid,nodev /boot_disk/autosvr/k_mod.img /__autoserver__/kernel_modules
mount -t squashfs -o ro,nosuid,nodev /boot_disk/autosvr/system.img /rofs_root
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"
hash -r
# XXX: suggest RENAME_NOREPLACE command
[ -r /bin/busybox ]
/bin/busybox ln -s usr/bin /static
/__autoserver__/ctrtool renameat2 -x /static /bin
trap 'exec /static/sh' EXIT
/static/busybox ln -s usr/sbin /sbin
exec "${autoserver_init:-/init_stage3}"
false
