#!/bin/sh

set -eu

[ 1 = "$$" ]
[ ! -f /proc/version ]

trap 'exec /bin/sh' EXIT

mount -t proc -o nosuid,nodev,noexec none /proc
mount -t sysfs -o nosuid,nodev,noexec none /sys
mount -t devtmpfs -o nosuid,noexec none /dev

SEQ=0
while [ ! -e "$autoserver_boot_dev" ]; do
	sleep 2
	SEQ="$((SEQ+1))"
	if [ "$SEQ" -gt 10 ]; then
		break
	fi
	printf 'Waiting for %s... (attempt %d)\n' "$autoserver_boot_dev" "$SEQ"
done

mount -t "${autoserver_boot_fstype:-vfat}" -o "${autoserver_boot_opts:-ro}" "$autoserver_boot_dev" "/boot_disk"
mount -t squashfs /boot_disk/autosvr/system.img /rofs_root
# XXX: suggest RENAME_NOREPLACE command
/bin/busybox mv /bin /static
trap 'exec /static/sh' EXIT
/static/busybox ln -s usr/bin /bin
/static/busybox ln -s usr/sbin /sbin
exec /init_stage3
false
