#!/bin/sh
set -euC
mkdir -p /build/busybox-d
bsdtar -xC /build/busybox-d -f /busybox.tar.bz2 --strip-components 1

printf 'CONFIG_%s=y\n' BASH_IS_ASH BBCONFIG FEATURE_UNIX_LOCAL PIE RFKILL \
VERBOSE_RESOLUTION_ERRORS FEATURE_PREFER_APPLETS > /build/busybox-d/.config
printf '# CONFIG_%s is not set\n' FEATURE_PREFER_IPV4_ADDRESS FEATURE_SH_EXTRA_QUIET \
>> /build/busybox-d/.config

printf 'CONFIG_EXTRA_CFLAGS="-fstack-protector-strong -D_FORTIFY_SOURCE=2"\nCONFIG_EXTRA_LDFLAGS="-z relro -z now"\n' >> /build/busybox-d/.config

yes "" | make -C /build/busybox-d oldconfig && make -C /build/busybox-d -j 8

cp -ar --reflink=auto /build/busybox-d /build/busybox-s
sed -i '/^CONFIG_PIE=/d;/^#/d;/^CONFIG_EXTRA_CFLAGS=/cCONFIG_EXTRA_CFLAGS="-static-pie -fstack-protector-strong -D_FORTIFY_SOURCE=2"' /build/busybox-s/.config
yes "" | make -C /build/busybox-s oldconfig && make -C /build/busybox-s -j 8

/build/busybox-d/busybox --list > /build/busybox-list
/build/busybox-d/busybox bbconfig > /build/busybox-config
# cp -a /build/busybox-d/busybox /output/busybox-d
# cp -a /build/busybox-s/busybox /output/busybox-s
