#!/bin/sh

set -eu

CLOUDIMG_VERSION='20230711-1438'
CLOUDIMG_SHA512SUM='c812ed7607fd4e0ef34f4e2cc9d3903a0b7883252bc902bfb3da7786b8ae3668ad65009056f22fc503bedc63a2419b2feffb84a3d62dccb13ff84fb065ab48cb'
wget -O debian.tar.xz "https://cloud.debian.org/images/cloud/bookworm/$CLOUDIMG_VERSION/debian-12-generic-amd64-$CLOUDIMG_VERSION.tar.xz"
if sha512sum debian.tar.xz | grep "^$CLOUDIMG_SHA512SUM "; then
	:
else
	echo >&2 'Incorrect checksum'
	exit 1
fi
bsdtar -xOf debian.tar.xz disk.raw > disk_raw.img
truncate -s 40G disk_raw.img
