#!/bin/sh

set -eu

CLOUDIMG_VERSION='20230802-1460'
CLOUDIMG_SHA512SUM='64aeb3a531561c6f470f6cd1831ec232eff10fc41926fba3f77c80e6b449acb44b78f9d0273687b452f595df888eab0033e4a02f27d8dc117b73bbde68d5192b'
wget -O debian.tar.xz "https://cloud.debian.org/images/cloud/bookworm/$CLOUDIMG_VERSION/debian-12-generic-amd64-$CLOUDIMG_VERSION.tar.xz"
if sha512sum debian.tar.xz | grep "^$CLOUDIMG_SHA512SUM "; then
	:
else
	echo >&2 'Incorrect checksum'
	exit 1
fi
bsdtar -xOf debian.tar.xz disk.raw > disk_raw.img
truncate -s 40G disk_raw.img
growpart disk_raw.img 1
