#!/bin/sh

set -eu

CLOUDIMG_VERSION='20230124-1270'
CLOUDIMG_SHA512SUM='aadbc6a551e58318c6ecb34ef03caf125e056a8b74e87e04cb04cc0614086b861cff52e29565de4f2b51cae983fe38c42ab04cacf9099e2b5714689c31a6283e'

wget -O debian.tar.xz "https://cloud.debian.org/images/cloud/bullseye/$CLOUDIMG_VERSION/debian-11-generic-amd64-$CLOUDIMG_VERSION.tar.xz"
if sha512sum debian.tar.xz | grep "^$CLOUDIMG_SHA512SUM "; then
	:
else
	echo >&2 'Incorrect checksum'
	exit 1
fi
bsdtar -xOf debian.tar.xz disk.raw > disk_raw.img
truncate -s 40G disk_raw.img
